// Generated by ts-to-zod
import { z } from "zod";

export const playerDataSchema = z.object({
    forename: z.string(),
    surname: z.string(),
    number: z.number().min(1),
    position: z.string()
});

export const teamDataSchema = z.object({
    id: z.string(),
    name: z.string(),
    shortName: z.string(),
    players: z.array(playerDataSchema),
    substitutes: z.array(playerDataSchema)
});

export const matchDataSchema = z.object({
    name: z.string(),
    home: teamDataSchema,
    away: teamDataSchema
});
