// Generated by ts-to-zod
import { z } from "zod";

export const teamLocationSchema = z.union([z.literal("home"), z.literal("away")]);

export const playerSchema = z.object({
    forename: z.string(),
    surname: z.string(),
    number: z.number().min(1),
    x: z.number().optional(),
    y: z.number().optional()
});

export const teamDataSchema = z.object({
    id: z.string(),
    location: teamLocationSchema,
    name: z.string(),
    shortName: z.string(),
    badgeSrc: z.string(),
    players: z.array(playerSchema),
    substitutes: z.array(playerSchema)
});

export const matchDataSchema = z.object({
    name: z.string(),
    home: teamDataSchema,
    away: teamDataSchema
});
