// Generated by ts-to-zod
import { z } from "zod";

export const teamLocationSchema = z.union([z.literal("home"), z.literal("away")]);

export const playerSchema = z.object({
    id: z.string(),
    forename: z.string(),
    surname: z.string(),
    number: z.number(),
    location: teamLocationSchema,
    x: z.number().optional(),
    y: z.number().optional()
});

export const teamDataSchema = z.object({
    location: teamLocationSchema,
    name: z.string(),
    shortName: z.string(),
    players: z.array(playerSchema),
    manager: z.string(),
    captain: z.string()
});

export const matchDataSchema = z.object({
    home: teamDataSchema,
    away: teamDataSchema
});
