// Generated by ts-to-zod
import { z } from "zod";

import { playerDataSchema, teamDataSchema, matchDataSchema } from "./data";

export const penaltyStateSchema = z.union([z.literal(0), z.literal(1), z.literal(2)]);

export const formationKeySchema = z.union([z.literal("3-4-3"), z.literal("3-5-2"), z.literal("3-4-2-1"), z.literal("3-6-1"), z.literal("4-3-3"), z.literal("4-4-2"), z.literal("4-5-1"), z.literal("4-4-1-1"), z.literal("4-3-2-1"), z.literal("4-2-3-1"), z.literal("5-4-1"), z.literal("5-3-2")]);

export const matchTimeSchema = z.object({
    paused: z.boolean(),
    ms: z.number(),
    formatted: z.string()
});

export const teamStateSchema = z.object({
    activeFormation: formationKeySchema,
    goals: z.array(playerDataSchema),
    penalties: z.tuple([penaltyStateSchema, penaltyStateSchema, penaltyStateSchema, penaltyStateSchema, penaltyStateSchema])
});

export const overlayStateSchema = z.object({
    visible: z.boolean()
});

export const graphicsSchema = z.object({
    matchScorecard: overlayStateSchema,
    penaltiesScorecard: overlayStateSchema,
    bigMatchScorecard: overlayStateSchema,
    teamFormation: overlayStateSchema,
    substitution: overlayStateSchema
});

export const initialStateSchema = z.object({
    matchTime: matchTimeSchema,
    home: teamStateSchema,
    away: teamStateSchema,
    graphics: graphicsSchema
});

export const teamCompleteSchema = teamDataSchema.and(teamStateSchema);

export const completeStateSchema = matchDataSchema.and(initialStateSchema);
