// Generated by ts-to-zod
import { z } from "zod";

import { playerSchema, teamLocationSchema } from "./data";

export const penaltyStateSchema = z.union([z.literal(0), z.literal(1), z.literal(2)]);

export const formationKeySchema = z.union([z.literal("3-4-3"), z.literal("3-5-2"), z.literal("3-4-2-1"), z.literal("3-6-1"), z.literal("4-3-3"), z.literal("4-4-2"), z.literal("4-5-1"), z.literal("4-4-1-1"), z.literal("4-3-2-1"), z.literal("4-2-3-1"), z.literal("5-4-1"), z.literal("5-3-2")]);

export const matchTimeSchema = z.object({
    paused: z.boolean(),
    ms: z.number(),
    formatted: z.string()
});

export const goalSchema = z.object({
    player: playerSchema,
    matchTime: matchTimeSchema
});

export const playerStateSchema = z.object({
    id: z.string(),
    number: z.number().min(1),
    x: z.number().optional(),
    y: z.number().optional()
});

export const teamStateSchema = z.object({
    activeFormation: formationKeySchema.optional(),
    players: z.array(playerStateSchema),
    substitutes: z.array(playerStateSchema),
    goals: z.array(goalSchema),
    penalties: z.tuple([penaltyStateSchema, penaltyStateSchema, penaltyStateSchema, penaltyStateSchema, penaltyStateSchema])
});

export const overlayStateSchema = z.object({
    name: z.string(),
    visible: z.boolean()
});

export const startingSoonDataUpdateSchema = z.object({
    kickoffTime: z.string()
});

export const startingSoonDataSchema = overlayStateSchema.and(startingSoonDataUpdateSchema);

export const pendingSubSchema = z.tuple([playerSchema, playerSchema]);

export const substitutionDataUpdateSchema = z.object({
    location: teamLocationSchema,
    subs: z.array(pendingSubSchema)
});

export const substitutionDataSchema = overlayStateSchema.and(substitutionDataUpdateSchema);

const teamFormationDataUpdateSchema = z.object({
    location: teamLocationSchema
});

export const teamFormationDataSchema = overlayStateSchema.and(teamFormationDataUpdateSchema);

export const graphicsSchema = z.object({
    startingSoon: startingSoonDataSchema,
    matchScorecard: overlayStateSchema,
    penaltiesScorecard: overlayStateSchema,
    bigMatchScorecard: overlayStateSchema,
    teamFormation: teamFormationDataSchema,
    substitution: substitutionDataSchema,
    hydrationBreak: overlayStateSchema,
});

export const initialStateSchema = z.object({
    matchTime: matchTimeSchema,
    home: teamStateSchema,
    away: teamStateSchema,
    graphics: graphicsSchema
});

export const teamCompleteSchema = z.object({
    location: teamLocationSchema,
    name: z.string(),
    shortName: z.string(),
    manager: z.string(),
    captain: playerSchema,
    activeFormation: formationKeySchema.optional(),
    players: z.array(playerSchema),
    substitutes: z.array(playerSchema),
    goals: z.array(goalSchema),
    penalties: z.tuple([penaltyStateSchema, penaltyStateSchema, penaltyStateSchema, penaltyStateSchema, penaltyStateSchema])
});

export const completeStateSchema = z.object({
    matchTime: matchTimeSchema,
    graphics: graphicsSchema,
    home: teamCompleteSchema,
    away: teamCompleteSchema
});
